// =========================================================
// Mock Data Store for Insect Database System
// Used as in-memory fallback when external DB server is offline
// =========================================================

export let categories = [
  {
    id: 1,
    name: 'Coleoptera (ด้วง)',
    description: 'แมลงที่มีปีกคู่หน้าแข็งปรีด ปีกคู่หลังใช้บิน เช่น ด้วงกว่าง ด้วงคีม',
    created_at: '2026-07-13 07:36:01'
  },
  {
    id: 2,
    name: 'Lepidoptera (ผีเสื้อและมอธ)',
    description: 'แมลงที่มีปีกเป็นแผ่นบางๆ คลุมด้วยเกล็ดสีสันสวยงาม',
    created_at: '2026-07-13 07:36:01'
  },
  {
    id: 3,
    name: 'Odonata (แมลงปอ)',
    description: 'แมลงที่มีตารวมขนาดใหญ่ ปีกบางยาวสองคู่ บินได้รวดเร็ว',
    created_at: '2026-07-13 07:36:01'
  }
];

export let contact_us = [
  {
    id: 5,
    first_name: 'พศิน',
    last_name: 'วีรวงค์',
    address: 'อยู่ปัว',
    phone: '0123456',
    comment: 'ฝนตก',
    created_at: '2026-08-13 08:38:54'
  }
];

export let users = [
  {
    id: 1,
    username: 'admin_insect',
    password: '$2b$10$nHDkD3QDCY771YgV3NaPT.SLIPoIdzgALJHMjjLxIP2MZARYXxCra',
    email: 'admin@insectdb.com',
    role: 'admin',
    created_at: '2026-07-13 07:36:01'
  },
  {
    id: 2,
    username: 'somchai_dev',
    password: '$2b$10$qjJz.BDM8ZWfz7G6lIqqn.GEfmGDXQh531tX67cv8dqUN1zs3C3v2',
    email: 'somchai@gmail.com',
    role: 'user',
    created_at: '2026-07-13 07:36:01'
  },
  {
    id: 3,
    username: 'pasin',
    password: '$2b$10$DbDIrVGbWt1BvqI0/E4gAOmXBwy1T5eRTlo8tab6nq3XHSwF5zypW',
    email: '12345@dssd.com',
    role: 'user',
    created_at: '2026-07-23 07:09:50'
  }
];

export let insects = [
  {
    id: 1,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างแดง',
    scientific_name: 'Xylotrupes gideon',
    description: 'กว่างแดง คือ กว่างชมที่มีปีกและลำตัวสีน้ำตาลแดง',
    habitat: 'ป่าดิบแล้ง ป่าเบญจพรรณ และป่าเต็งรัง',
    status: 'protected',
    image_url: '/uploads/1787547295416-IMG_20260824_115232.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Scarabaeidae',
    genus: 'Xylotrupes',
    species: 'Xylotrupes gideon',
    mouth_type: 'กัดกิน (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาขุดดิน/เดิน (Cursorial)',
    antenna_type: 'หนวดแบบใบไม้ (Lamellate)',
    region: 'ภาคเหนือ',
    province: 'จังหวัดเชียงใหม่, เชียงราย, น่าน, พะเยา, ลำปาง, ลำพูน, แพร่ และแม่ฮ่องสอน',
    source: '',
    created_at: '2026-08-24 04:01:41',
    updated_at: '2026-08-28 05:43:58'
  },
  {
    id: 2,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างฮัก',
    scientific_name: 'Xylotrupes socrates Schaufuss',
    description: 'กว่างฮัก คือ กว่างชนที่มีปีก ขา หัวและลำตัวสีดำ',
    habitat: 'ป่าโปร่งและชุมชนชนบทที่มีความชุ่มชื้น',
    status: 'protected',
    image_url: '/uploads/1787551117944-IMG_20260824_123208.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Scarabaeidae',
    genus: 'Xylotrupes',
    species: 'Xylotrupes socrates',
    mouth_type: 'เคี้ยวตัด (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบข้อหัก (Geniculate)',
    region: 'ภาคเหนือ',
    province: 'เชียงใหม่, น่าน, เชียงราย, พะเยา, ลำปาง, ลำพูน, แพร่, แม่ฮ่องสอน, อุตรดิตถ์ และตาก',
    source: 'ลิงก์แหล่งที่มาของข้อมูล ฐานข้อมูลความหลากหลายทางชีวภาพ สำนักงานนโยบายและแผนทรัพยากรธรรมชาติและสิ่งแวดล้อม (ONEP: Xylotrupes gideon) สมาคมพัฒนาคุณภาพสิ่งแวดล้อม (ADEQ) - กว่างชน/กว่างโซ้ง วิกิพีเดีย - ด้วงกว่างชนและวัฒนธรรมการชนกว่างในล้านนา',
    created_at: '2026-08-24 06:03:03',
    updated_at: '2026-08-28 05:40:33'
  },
  {
    id: 3,
    category_id: 2,
    category_name: 'Lepidoptera (ผีเสื้อและมอธ)',
    common_name: 'ผีเสื้อหางติ่งสะพานฟ้า',
    scientific_name: 'Graphium sarpedon',
    description: 'ผีเสื้อกลางวันที่มีแถบสีฟ้าสดใสพาดผ่านกลางปีก',
    habitat: 'สวนผลไม้ และชายป่าดิบ',
    status: 'common',
    image_url: '/uploads/1784198083420-images.jfif',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Papilionidae',
    genus: 'Graphium',
    species: 'Graphium sarpedon',
    mouth_type: 'ดูดกิน (Siphoning)',
    wing_type: 'ปีกเกล็ด (Scaly wings)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบรูปกระบอง (Clavate)',
    region: 'ภาคกลาง',
    province: 'นครนายก',
    source: 'อุทยานแห่งชาติเขาใหญ่',
    created_at: '2026-07-13 07:36:01',
    updated_at: '2026-07-16 10:34:44'
  },
  {
    id: 4,
    category_id: 3,
    category_name: 'Odonata (แมลงปอ)',
    common_name: 'แมลงปอเข็มท้องยาว',
    scientific_name: 'Ischnura senegalensis',
    description: 'แมลงปอขนาดเล็ก ลำตัวผอมยาว มักพบบริเวณแหล่งน้ำนิ่ง',
    habitat: 'หนอง บึง และทุ่งนา',
    status: 'common',
    image_url: '/uploads/1784198252075-_________________.webp',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Coenagrionidae',
    genus: 'Ischnura',
    species: 'Ischnura senegalensis',
    mouth_type: 'เคี้ยวเอื้อง (Chewing)',
    wing_type: 'ปีกบางใส (Membranous)',
    leg_type: 'ขาจับเหยื่อ (Raptorial)',
    antenna_type: 'หนวดแบบขนสั้น (Setaceous)',
    region: 'ภาคตะวันออกเฉียงเหนือ',
    province: 'ขอนแก่น',
    source: 'บึงแก่นนคร',
    created_at: '2026-07-13 07:36:01',
    updated_at: '2026-07-16 10:37:32'
  },
  {
    id: 16,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างแซม',
    scientific_name: 'Xylotrupes siamensis',
    description: '"กว่างแซม" เป็นกว่างชนเพศผู้ที่มีขนาดกลาง ลำตัวใหญ่กว่ากว่างกิหรืออาจเท่ากว่างกิโตน แต่ลำตัวจะบอบบางกว่ากิโตนและเขาจะเรียวยาวกว่าแต่ขนาดจะเล็กกว่ากว่างโซ้ง กว่างแซมมีขนาดลำตัวถึงปลายเขายาว 50-64 ม.ม. กว้าง 21-25 ม.ม. กว่างแซมใช้ในการชนหรือประกวดกว่างสวยงามได้ ถ้าเป็นแซมเล็กจะถูกใช้เป็นกว่างต่อ กว่างล่อหรือกว่างตั้ง',
    habitat: 'ป่าดิบแล้ง ป่าเบญจพรรณ และป่าเต็งรัง',
    status: 'common',
    image_url: '/uploads/1787552491686-IMG_20260824_130718.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Scarabaeidae',
    genus: 'Xylotrupes',
    species: 'Xylotrupes siamensis',
    mouth_type: 'กัดกิน (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบใบไม้ (Lamellate)',
    region: 'ภาคเหนือ',
    province: 'ลำปาง',
    source: '',
    created_at: '2026-08-24 06:21:33',
    updated_at: '2026-08-24 06:24:03'
  },
  {
    id: 17,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างโซ้ง',
    scientific_name: 'Xylotrupes siamensis',
    description: '"กว่างโซ้ง" เป็นกว่างชนเพศผู้ที่มีขนาดใหญ่กว่ากว่างชนประเภทอื่น ลำตัวและเขาจะมีขนาดที่ใหญ่และยาวสวยงาม มีขนาดลำตัวถึงปลายเขายาวตั้งแต่ 65 ม.ม.ขึ้นไป ขนาดลำตัวกว้างมากกว่า 25 ม.ม. กว่างโซ้งนิยมใช้ในการชนหรือประกวดกว่างสวยงาม',
    habitat: 'ป่าเบญจพรรณและป่าดิบแล้ง',
    status: 'common',
    image_url: '/uploads/1787553747553-IMG_20260824_133040.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Scarabaeidae',
    genus: 'Xylotrupes',
    species: 'Xylotrupes gideon',
    mouth_type: 'กัดกิน (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบใบไม้ (Lamellate)',
    region: 'ภาคเหนือ',
    province: 'เชียงราย, เชียงใหม่, พะเยา, น่าน, ลำพูน, แพร่, แม่ฮ่องสอน, ตาก',
    source: '',
    created_at: '2026-08-24 06:43:41',
    updated_at: '2026-08-28 05:24:02'
  },
  {
    id: 18,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างกิโตนหรือกิดง',
    scientific_name: 'Xylotrupes gideon',
    description: '"กว่างกิโตน" เป็นกว่างชนเพศผู้ที่มีขนาดใหญ่กว่ากว่างกิ ลำตัวอาจมีขนาดเท่ากว่างแซม แต่เขาจะสั้นกว่าเขากว่างแซมและมักมีเขาล่างจะยาวกว่าเขาบน มีขนาดลำตัวยาว 40-50 ม.ม. กว้าง 20-25 ม.ม. เขาบนยาว 5-8 ม.ม. เขาล่างยาว 10-15 ม.ม. ใช้เป็นกว่างต่อ กว่างล่อหรือกว่างตั้งได้ และสามารถนำมาชนได้ดีเพราะเป็นกว่างที่แข็งแรงและมีความอดทน',
    habitat: 'ป่าเบญจพรรณหรือพื้นที่เกษตรกรรม',
    status: 'common',
    image_url: '/uploads/1787555041801-IMG_20260824_134617.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Scarabaeidae',
    genus: 'Xylotrupes',
    species: 'Xylotrupes gideon',
    mouth_type: 'กัดกิน (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบใบไม้ (Lamellate)',
    region: 'ภาคเหนือ',
    province: 'น่าน, เชียงใหม่, เชียงราย, ลำปาง, ลำพูน, พะเยา, แพร่, แม่ฮ่องสอน',
    source: 'สำนักส่งเสริมศิลปวัฒนธรรมและล้านนาสร้างสรรค์ มหาวิทยาลัยเชียงใหม่ (เรื่อง วัฒนธรรมและประเภทของกว่างล้านนา): https://art-culture.cmu.ac.th วิกิพีเดีย ภาษาไทย (ด้วงกว่างชน): https://th.wikipedia.org/wiki/ด้วงกว่างชน ศูนย์ข้อมูลกลางทางวัฒนธรรม กระทรวงวัฒนธรรม',
    created_at: '2026-08-24 07:04:05',
    updated_at: '2026-08-28 05:13:26'
  },
  {
    id: 19,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างแม่โม๊ะ',
    scientific_name: 'Xylotrupes socrates',
    description: '"กว่างแม่โม๊ะ" เป็นกว่างชนเพศเมีย ไม่มีเขา มีขนาดลำตัวยาว 30-40 ม.ม. กว้าง 15-20 ม.ม. กว่างแม่โม๊ะ นอกจากมีไว้เพื่อการขยายพันธุ์แล้วยังใช้ในการชนกว่างโดยใช้เป็นตัวกระตุ้นกว่างชนเพศผู้ เมื่อกว่างชนเพศผู้ดมกลิ่นเพศเมียซึ่งเป็นกลิ่นฟีโรโมนเพศ ทำให้กว่างเพศผู้คึกคะนองและเกิดการแย่งชิงกว่างเพศเมียจนมีการชนกันขึ้นเพื่อผู้ชนะจะได้ครอบครองกว่างเพศเมีย',
    habitat: 'ป่าเบญจพรรณและป่าดิบชื้น',
    status: 'common',
    image_url: '/uploads/1787556214475-IMG_20260824_142214.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Dynastinae',
    genus: 'Xylotrupes',
    species: 'Xylotrupes gideon',
    mouth_type: 'กัดกิน (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบใบไม้ (Lamellate)',
    region: 'ภาคเหนือ',
    province: 'น่าน พะเยา เชียงใหม่, เชียงราย, แพร่, น่าน, ลำปาง, ลำพูน, แม่ฮ่องสอน',
    source: '',
    created_at: '2026-08-24 07:24:46',
    updated_at: '2026-08-28 05:06:44'
  },
  {
    id: 20,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างกิ',
    scientific_name: 'Xylotrupes gideon (Linnaeus, 1767)',
    description: '"กว่างกิ" เป็นกว่างชนเพศผู้ที่มีขนาดเล็กและเขาสั้นที่สุด เขาล่างมักยาวกว่าเขาบน มีขนาดลำตัวยาว 30-40 ม.ม. กว้าง 15-20 ม.ม. เขาบนยาว 5-8 ม.ม. เขาล่างยาว 10-15 ม.ม. กว่างกิไม่เหมาะสำหรับการชนหรือประกวดกว่างสวยงามแต่จะถูกใช้เป็นกว่างต่อ กว่างล่อหรือกว่างตั้ง เพื่อล่อให้กว่างชนทั้งเพศผู้และเพศเมียอื่นๆ มาติดกับ',
    habitat: 'ป่าเบญจพรรณและป่าดิบแล้ง',
    status: 'common',
    image_url: '/uploads/1787557359139-IMG_20260824_143156.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Scarabaeidae',
    genus: 'Xylotrupes',
    species: 'Xylotrupes socrates',
    mouth_type: 'กัดกิน (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบใบไม้ (Lamellate)',
    region: 'ภาคเหนือ',
    province: 'เชียงใหม่ เชียงราย พะเยา น่าน ลำปาง, ลำพูน, แพร่, แม่ฮ่องสอน',
    source: '',
    created_at: '2026-08-24 07:42:41',
    updated_at: '2026-08-28 04:46:30'
  },
  {
    id: 21,
    category_id: 1,
    category_name: 'Coleoptera (ด้วง)',
    common_name: 'กว่างห้าเขา, กว่างซางเหนือ',
    scientific_name: 'Eupatorus gracilicornis',
    description: 'กว่างซางเหนือหรือกว่างห้าเขา พบในแถบภาคเหนือตอนบนของประเทศไทย ได้แก่ จังหวัดเชียงราย พะเยา แพร่ ลำพูน ลำปาง เชียงใหม่ แม่ฮ่องสอน อุตรดิตถ์และน่าน\nตัวเต็มวัยมีลักษณะของลำตัว ขาและส่วนหัวเป็นสีดำมันวาว ปีกคู่หน้าเป็นแบบเกราะแข็ง (elytra) มีสีน้ำตาลอ่อน ปีกคู่หลังเป็นแบบเนื้อเยื่อ (membranous) มีหนวดแบบใบไม้ (lamellate) เพศเมียไม่มีเขา ลำตัวยาวเฉลี่ย 52.67±3.71 มม. กว้างเฉลี่ย 27.52±2.08 มม. เพศผู้มีเขา 5 เขา ปลายเขาแหลมไม่เป็นแฉก มีขนาดลำตัวยาวเฉลี่ย 70.75±11.83 มม. กว้างเฉลี่ย 31.45±2.30 มม.เพศเมีย : สีเหมือนเพศผู้แต่ไม่มีเขา, ขนาด : 40-65 มิลลิเมตร\nระยะหนอนจะอาศัยอยู่ในดินที่มีอินทรียวัตถุเน่าเปื่อยหรืออยู่ในกอไผ่ซางที่ตายผุพังย่อยสลายเป็นอินทรียวัตถุแล้ว โดยอาหารของหนอนกว่างซางเหนือจะกินใบไม้ผุ ไม้ผุและกอไผ่ผุในป่า หนอนจะขับถ่ายมูลออกมาเป็นปุ๋ยให้แก่พืชในป่าซึ่งเป็นการหมุนเวียนธาตุอาหารพืชในระบบนิเวศจังหวัดน่าน พบทุกอำเภอ ตัวเต็มวัยพบช่วงเดือนสิงหาคม-ตุลาคม พบในที่สูงตั้งแต่ 300-1,500 เมตรจากระดับน้ำทะเล มีพืชอาศัย คือ ไผ่ซาง ไผ่หก',
    habitat: 'ป่าดิบชื้นและป่าบนภูเขาสูง',
    status: 'protected',
    image_url: '/uploads/1787559841687-5____.jpg',
    kingdom: 'Animalia',
    phylum: 'Arthropoda',
    class_name: 'Insecta',
    family: 'Scarabaeidae',
    genus: 'Eupatorus',
    species: 'Eupatorus gracilicornis',
    mouth_type: 'กัดกิน (Chewing)',
    wing_type: 'ปีกแข็ง (Elytra)',
    leg_type: 'ขาเดิน (Cursorial)',
    antenna_type: 'หนวดแบบใบไม้ (Lamellate)',
    region: 'ภาคเหนือ',
    province: 'เชียงราย พะเยา แพร่ ลำพูน ลำปาง เชียงใหม่ แม่ฮ่องสอน อุตรดิตถ์ น่าน',
    source: '',
    created_at: '2026-08-24 08:30:00',
    updated_at: '2026-08-27 07:56:41'
  }
];
